### ISSUE TITLE
How to mutate nodes?

### ISSUE THREAD

**Issue by vmarkovtsev** [bblfsh/go-client#113]
My next question is: OK, I know how to retrieve attribute values using `uast.TokenOf`, `uast.PositionsOf`, etc., but how can I change those values in some nodes? There are no `uast.Set*` counterparts...

**Comment by vmarkovtsev** [comment]
My current code to erase the end position in `node`:

```go
obj, _ := node.(nodes.Object)[uast.KeyPos].(nodes.Object)
if len(obj) == 0 {
	return
}
obj[uast.KeyEnd] = nil
```

**Comment by dennwc** [comment]
The first option is to directly change schema-less nodes - this is exactly what you do right now. Although I would suggest removing the end key completely:
```golang
delete(obj, uast.KeyEnd)
```
The second option is to first convert to Go objects, change the node, and then convert back:
```golang
pos := make(uast.Positions)
err := uast.NodeAs(node, &pos)

delete(pos, uast.KeyEnd)
node, err = uast.ToNode(pos)
```
It may be slower, but it will offer auto-completion and the code may be a bit nicer.
